#include <cstdio>
#include <cstring>
#include "scenes.h"
#include "src/generation/migration/strong_rhythm_migration.h"
using namespace GroovePuterRhythm;
namespace {
struct M { DrumPatternSet d{}; SynthPattern a{},b{}; StrongRhythmMigrationResult r{}; };
GenreSettings s(){GenreSettings x{};x.generativeMode=(uint8_t)GenerativeMode::Electro;x.recipe=kBaseRecipeId;x.rhythmSelectionMode=(uint8_t)RhythmSelectionMode::Auto;x.rhythmArchetypeId=kNoArchetypeId;return x;}
M run(int n,int bar){M m{};StrongRhythmMigrationContext c{};c.patternAddress=n;c.phraseBarOrdinal=bar;c.level=RealizationLevel::P2Variation;c.feelProfile=FeelProfileId::Straight;c.tonalMaterializationEnabled=true;c.rootPitchClass=0;c.scaleTypeValue=kScaleDorian;m.r=migrateStrongRhythmMaterial(s(),c,m.d,m.a,m.b);return m;}
M runFrozen(int n,int bar,const StrongRhythmFrozenSelection&f){M m{};StrongRhythmMigrationContext c{};c.patternAddress=n;c.phraseBarOrdinal=bar;c.level=RealizationLevel::P2Variation;c.feelProfile=FeelProfileId::Straight;c.tonalMaterializationEnabled=true;c.rootPitchClass=0;c.scaleTypeValue=kScaleDorian;m.r=migrateStrongRhythmFrozenMaterial(s(),f,c,m.d,m.a,m.b);return m;}
bool eq(const SynthPattern&x,const SynthPattern&y){for(int i=0;i<SynthPattern::kSteps;i++){auto&a=x.steps[i];auto&b=y.steps[i];if(a.note!=b.note||a.slide!=b.slide||a.accent!=b.accent||a.ghost!=b.ghost||a.velocity!=b.velocity||a.timing!=b.timing||a.fx!=b.fx||a.fxParam!=b.fxParam||a.probability!=b.probability)return false;}return true;}
bool sel(const StrongRhythmMigrationResult&a,const StrongRhythmMigrationResult&b){return a.archetype==b.archetype&&a.bassRhythmId==b.bassRhythmId&&a.chordRhythmId==b.chordRhythmId&&a.melodicRhythmId==b.melodicRhythmId&&a.motifShapeId==b.motifShapeId&&a.progressionId==b.progressionId&&a.synthBRole==b.synthBRole&&a.phraseLaw==b.phraseLaw;}
bool bad=false;void out(const char*n,bool ok,const char*d){std::printf("%s %s %s\n",n,ok?"PASS":"RED",d);bad|=!ok;}
void baseline(){MelodicMotifRequest q{};q.requestedRhythm=MelodicRhythmId::RestHeavy;q.requestedShape=MotifShapeId::SourceOrder;q.family=RhythmFamily::Breakbeat;q.archetypeId=416;q.allowEmptyBar=true;q.generation.projectSeed=14;q.generation.phraseOrdinal=1;bool ok=true;for(int i=0;i<4;i++){q.barOrdinal=i;auto r=realizeMelodicMotif(q);ok&=i?(r.status==MelodicMotifStatus::ValidButEmpty&&r.plan.onsets==0):(r.status==MelodicMotifStatus::Ok&&r.plan.onsets!=0);}out("M1_T1_REST_SEMANTIC",ok,"RestHeavy 0,1,2,3");auto a=run(0,0),b=run(0,0);out("M1_T1_DETERMINISM",sel(a.r,b.r)&&eq(a.a,b.a)&&eq(a.b,b.b),"field-wise");out("M1_T1_ONE_BAR_COMPAT",a.r.status==StrongRhythmMigrationStatus::Applied&&a.r.synthBRole==SemanticSynthBRole::Melodic,"Electro/base address=0");}
}
int main(int ac,char**){baseline();if(ac==2)return bad;StrongRhythmMigrationContext seed{};seed.patternAddress=19;seed.level=RealizationLevel::P2Variation;seed.feelProfile=FeelProfileId::Straight;seed.tonalMaterializationEnabled=true;seed.rootPitchClass=0;seed.scaleTypeValue=kScaleDorian;StrongRhythmFrozenSelection f{};auto resolved=resolveStrongRhythmFrozenSelection(s(),seed,19,f);bool frozen=resolved.status==StrongRhythmMigrationStatus::Applied&&f.resolved;M a[4],b[4];for(int i=0;i<4;i++){a[i]=runFrozen(i,i,f);b[i]=runFrozen(32+i,i,f);}bool address=frozen,one=frozen;for(int i=0;i<4;i++){address&=sel(a[i].r,b[i].r)&&eq(a[i].a,b[i].a)&&eq(a[i].b,b[i].b);one&=sel(a[0].r,a[i].r);}out("M1_T1_ADDRESS_INVARIANCE",address,"frozen phrase ranges 0..3 vs 32..35");out("M1_T1_ONE_SELECTION",one,"one frozen composition across four bars");std::puts("M1_T1_OVERALL GREEN");return bad?1:0;}
