// Generated by tools/idiom/gen_idiom_tables.py from the SEQTRAK genre
// dataset (track_patterns.csv) + hand-written House. Do not edit by hand.
#pragma once

#include "genre_idiom_types.h"

namespace GenreIdiom {

inline constexpr IdiomNote k_acid_chicago_jack_P1_bass[] = {{0, 0, 1, 110, 1}, {2, 0, 1, 76, 0}, {3, 3, 1, 92, 0}, {5, 0, 1, 72, 0}, {6, 7, 1, 104, 2}, {8, 0, 1, 116, 1}, {9, -2, 1, 80, 0}, {11, 0, 1, 96, 0}, {13, 3, 1, 84, 0}, {14, 7, 1, 108, 2}};
inline constexpr IdiomStab k_acid_chicago_jack_P1_stab[] = {{2, 0, 0x89u, 1, 72}, {6, 0, 0x89u, 1, 76}, {10, 10, 0x91u, 1, 70}, {14, 0, 0x89u, 1, 80}};
inline constexpr IdiomNote k_acid_chicago_jack_P1_melody[] = {{7, 12, 1, 62, 0}, {15, 7, 1, 68, 0}};
inline constexpr IdiomNote k_acid_chicago_jack_P2_bass[] = {{0, 0, 1, 112, 1}, {1, -5, 1, 70, 0}, {2, 0, 1, 78, 0}, {3, 3, 1, 94, 0}, {5, 0, 1, 74, 0}, {6, 7, 1, 106, 2}, {7, 3, 1, 68, 0}, {8, 0, 1, 118, 1}, {9, -2, 1, 82, 0}, {11, 0, 1, 98, 0}, {13, 3, 1, 86, 0}, {14, 7, 1, 110, 2}, {15, 12, 1, 72, 0}};
inline constexpr IdiomStab k_acid_chicago_jack_P2_stab[] = {{2, 0, 0x89u, 1, 74}, {6, 0, 0x89u, 1, 78}, {10, 10, 0x91u, 1, 72}, {14, 0, 0x89u, 1, 82}};
inline constexpr IdiomNote k_acid_chicago_jack_P2_melody[] = {{5, 15, 1, 52, 0}, {7, 12, 1, 64, 0}, {15, 7, 1, 72, 0}};
inline constexpr IdiomNote k_acid_chicago_jack_P3_bass[] = {{0, 0, 1, 108, 1}, {2, 0, 1, 74, 0}, {3, 3, 1, 90, 0}, {6, 7, 1, 102, 2}, {8, 0, 1, 114, 1}, {11, 0, 1, 92, 0}, {14, 7, 1, 106, 2}, {15, 12, 1, 66, 0}};
inline constexpr IdiomStab k_acid_chicago_jack_P3_stab[] = {{2, 0, 0x89u, 1, 70}, {10, 10, 0x91u, 1, 68}};
inline constexpr IdiomNote k_acid_chicago_jack_P3_melody[] = {{15, 12, 1, 74, 0}};
inline constexpr IdiomNote k_acid_rolling_P1_bass[] = {{0, 0, 1, 114, 1}, {1, -5, 1, 72, 0}, {2, 0, 1, 80, 0}, {3, 3, 1, 96, 0}, {5, 0, 1, 74, 0}, {6, 7, 1, 108, 2}, {7, 3, 1, 70, 0}, {8, 0, 1, 118, 1}, {9, -2, 1, 82, 0}, {10, 0, 1, 76, 0}, {11, 12, 1, 100, 2}, {13, 3, 1, 88, 0}, {14, 7, 1, 112, 1}, {15, 12, 1, 74, 2}};
inline constexpr IdiomStab k_acid_rolling_P1_stab[] = {{2, 0, 0x89u, 1, 72}, {6, 0, 0x89u, 1, 76}, {10, 10, 0x91u, 1, 70}, {14, 0, 0x89u, 1, 80}};
inline constexpr IdiomNote k_acid_rolling_P1_melody[] = {{7, 12, 1, 62, 0}, {15, 7, 1, 68, 0}};
inline constexpr IdiomNote k_acid_rolling_P2_bass[] = {{0, 0, 1, 112, 1}, {1, -5, 1, 70, 0}, {2, 0, 1, 78, 0}, {3, 3, 1, 94, 0}, {5, 0, 1, 74, 0}, {6, 7, 1, 106, 2}, {7, 3, 1, 68, 0}, {8, 0, 1, 118, 1}, {9, -2, 1, 82, 0}, {11, 0, 1, 98, 0}, {13, 3, 1, 86, 0}, {14, 7, 1, 110, 2}, {15, 12, 1, 72, 0}};
inline constexpr IdiomStab k_acid_rolling_P2_stab[] = {{2, 0, 0x89u, 1, 74}, {6, 0, 0x89u, 1, 78}, {10, 10, 0x91u, 1, 72}, {14, 0, 0x89u, 1, 82}};
inline constexpr IdiomNote k_acid_rolling_P2_melody[] = {{5, 15, 1, 52, 0}, {7, 12, 1, 64, 0}, {15, 7, 1, 72, 0}};
inline constexpr IdiomNote k_acid_rolling_P3_bass[] = {{0, 0, 1, 108, 1}, {2, 0, 1, 74, 0}, {3, 3, 1, 90, 0}, {6, 7, 1, 102, 2}, {8, 0, 1, 114, 1}, {11, 0, 1, 92, 0}, {14, 7, 1, 106, 2}, {15, 12, 1, 66, 0}};
inline constexpr IdiomStab k_acid_rolling_P3_stab[] = {{2, 0, 0x89u, 1, 70}, {10, 10, 0x91u, 1, 68}};
inline constexpr IdiomNote k_acid_rolling_P3_melody[] = {{15, 12, 1, 74, 0}};
inline constexpr IdiomNote k_lofi_classic_chill_P1_bass[] = {{0, 0, 2, 94, 0}, {3, -5, 2, 72, 0}, {6, -2, 2, 84, 0}, {10, 0, 2, 88, 0}, {13, -5, 2, 70, 0}};
inline constexpr IdiomStab k_lofi_classic_chill_P1_stab[] = {{0, 0, 0x489u, 6, 82}, {8, 8, 0x891u, 4, 74}, {12, 7, 0x489u, 3, 70}};
inline constexpr IdiomNote k_lofi_classic_chill_P1_melody[] = {{5, 7, 2, 62, 0}, {14, 3, 1, 58, 0}};
inline constexpr IdiomNote k_lofi_classic_chill_P2_bass[] = {{0, 0, 2, 94, 0}, {3, -5, 2, 72, 0}, {6, -2, 2, 84, 0}, {9, 3, 1, 66, 0}, {10, 0, 2, 88, 0}, {13, -5, 2, 70, 0}};
inline constexpr IdiomStab k_lofi_classic_chill_P2_stab[] = {{0, 0, 0x4489u, 6, 84}, {8, 8, 0x891u, 4, 76}, {12, 7, 0x489u, 3, 72}};
inline constexpr IdiomNote k_lofi_classic_chill_P2_melody[] = {{5, 7, 2, 62, 0}, {11, 10, 1, 50, 0}, {14, 3, 1, 60, 0}};
inline constexpr IdiomNote k_lofi_classic_chill_P3_bass[] = {{0, 0, 4, 88, 0}, {6, -2, 3, 74, 0}, {13, -5, 2, 64, 0}};
inline constexpr IdiomStab k_lofi_classic_chill_P3_stab[] = {{0, 0, 0x489u, 8, 78}, {12, 7, 0x489u, 3, 64}};
inline constexpr IdiomNote k_lofi_classic_chill_P3_melody[] = {{14, 3, 1, 56, 0}};
inline constexpr IdiomNote k_lofi_drunken_P1_bass[] = {{0, 0, 2, 94, 0}, {3, -5, 2, 72, 0}, {6, -2, 2, 84, 0}, {10, 0, 2, 88, 0}, {13, -5, 2, 70, 0}};
inline constexpr IdiomStab k_lofi_drunken_P1_stab[] = {{0, 0, 0x489u, 6, 82}, {8, 8, 0x891u, 4, 74}, {12, 7, 0x489u, 3, 70}};
inline constexpr IdiomNote k_lofi_drunken_P1_melody[] = {{5, 7, 2, 62, 0}, {14, 3, 1, 58, 0}};
inline constexpr IdiomNote k_lofi_drunken_P2_bass[] = {{0, 0, 2, 94, 0}, {3, -5, 2, 72, 0}, {6, -2, 2, 84, 0}, {9, 3, 1, 66, 0}, {10, 0, 2, 88, 0}, {13, -5, 2, 70, 0}};
inline constexpr IdiomStab k_lofi_drunken_P2_stab[] = {{0, 0, 0x4489u, 6, 84}, {8, 8, 0x891u, 4, 76}, {12, 7, 0x489u, 3, 72}};
inline constexpr IdiomNote k_lofi_drunken_P2_melody[] = {{5, 7, 2, 62, 0}, {11, 10, 1, 50, 0}, {14, 3, 1, 60, 0}};
inline constexpr IdiomNote k_lofi_drunken_P3_bass[] = {{0, 0, 4, 88, 0}, {6, -2, 3, 74, 0}, {13, -5, 2, 64, 0}};
inline constexpr IdiomStab k_lofi_drunken_P3_stab[] = {{0, 0, 0x489u, 8, 78}, {12, 7, 0x489u, 3, 64}};
inline constexpr IdiomNote k_lofi_drunken_P3_melody[] = {{14, 3, 1, 56, 0}};
inline constexpr IdiomNote k_boombap_golden_era_P1_bass[] = {{0, 0, 2, 100, 0}, {3, 3, 2, 76, 0}, {6, -5, 3, 90, 0}, {10, -2, 2, 82, 0}, {14, -5, 1, 74, 0}};
inline constexpr IdiomStab k_boombap_golden_era_P1_stab[] = {{0, 0, 0x4489u, 7, 92}, {8, 5, 0x4489u, 7, 84}};
inline constexpr IdiomNote k_boombap_golden_era_P1_melody[] = {{6, 7, 1, 60, 0}, {14, 10, 1, 64, 0}};
inline constexpr IdiomNote k_boombap_golden_era_P2_bass[] = {{0, 0, 2, 100, 0}, {3, 3, 2, 76, 0}, {6, -5, 3, 90, 0}, {9, -4, 1, 66, 0}, {10, -2, 2, 82, 0}, {14, -5, 1, 74, 0}};
inline constexpr IdiomStab k_boombap_golden_era_P2_stab[] = {{0, 0, 0x4489u, 7, 92}, {8, 5, 0x4489u, 5, 84}, {14, 7, 0x2411u, 2, 62}};
inline constexpr IdiomNote k_boombap_golden_era_P2_melody[] = {{6, 7, 1, 60, 0}, {11, 12, 1, 52, 0}, {14, 10, 1, 66, 0}};
inline constexpr IdiomNote k_boombap_golden_era_P3_bass[] = {{0, 0, 4, 94, 0}, {6, -5, 3, 84, 0}, {10, -2, 3, 76, 0}};
inline constexpr IdiomStab k_boombap_golden_era_P3_stab[] = {{0, 0, 0x4489u, 8, 88}, {12, 7, 0x2411u, 3, 72}};
inline constexpr IdiomNote k_boombap_golden_era_P3_melody[] = {{14, 10, 1, 62, 0}};
inline constexpr IdiomNote k_boombap_dusty_jazz_P1_bass[] = {{0, 0, 2, 100, 0}, {3, 3, 2, 76, 0}, {6, -5, 3, 90, 0}, {10, -2, 2, 82, 0}, {14, -5, 1, 74, 0}};
inline constexpr IdiomStab k_boombap_dusty_jazz_P1_stab[] = {{0, 0, 0x24489u, 7, 92}, {8, 5, 0x24489u, 7, 84}};
inline constexpr IdiomNote k_boombap_dusty_jazz_P1_melody[] = {{6, 7, 1, 60, 0}, {14, 10, 1, 64, 0}};
inline constexpr IdiomNote k_boombap_dusty_jazz_P2_bass[] = {{0, 0, 2, 100, 0}, {3, 3, 2, 76, 0}, {6, -5, 3, 90, 0}, {9, -4, 1, 66, 0}, {10, -2, 2, 82, 0}, {14, -5, 1, 74, 0}};
inline constexpr IdiomStab k_boombap_dusty_jazz_P2_stab[] = {{0, 0, 0x24489u, 7, 92}, {8, 5, 0x24489u, 5, 84}, {14, 1, 0x4491u, 2, 62}};
inline constexpr IdiomNote k_boombap_dusty_jazz_P2_melody[] = {{5, 15, 1, 54, 0}, {11, 9, 1, 58, 0}, {14, 10, 1, 62, 0}};
inline constexpr IdiomNote k_boombap_dusty_jazz_P3_bass[] = {{0, 0, 4, 94, 0}, {6, -5, 3, 84, 0}, {10, -2, 3, 76, 0}};
inline constexpr IdiomStab k_boombap_dusty_jazz_P3_stab[] = {{0, 0, 0x24489u, 8, 88}, {12, 1, 0x4491u, 3, 72}};
inline constexpr IdiomNote k_boombap_dusty_jazz_P3_melody[] = {{14, 10, 1, 62, 0}};
inline constexpr IdiomNote k_ukg_classic_2step_P1_bass[] = {{0, 0, 3, 108, 0}, {5, -5, 2, 86, 0}, {9, -2, 3, 96, 0}, {14, 3, 1, 82, 0}};
inline constexpr IdiomStab k_ukg_classic_2step_P1_stab[] = {{2, 0, 0x489u, 1, 76}, {6, 8, 0x891u, 1, 82}, {10, 10, 0x91u, 1, 72}, {14, 7, 0x489u, 1, 86}};
inline constexpr IdiomNote k_ukg_classic_2step_P1_melody[] = {{3, 7, 1, 64, 0}, {11, 10, 1, 70, 0}};
inline constexpr IdiomNote k_ukg_classic_2step_P2_bass[] = {{0, 0, 3, 108, 0}, {5, -5, 2, 86, 0}, {8, -4, 1, 70, 0}, {9, -2, 3, 98, 0}, {14, 3, 1, 84, 0}};
inline constexpr IdiomStab k_ukg_classic_2step_P2_stab[] = {{2, 0, 0x4489u, 1, 78}, {6, 8, 0x891u, 1, 84}, {10, 10, 0x291u, 1, 74}, {14, 7, 0x489u, 1, 88}};
inline constexpr IdiomNote k_ukg_classic_2step_P2_melody[] = {{3, 7, 1, 64, 0}, {9, 5, 1, 52, 0}, {11, 10, 1, 72, 0}};
inline constexpr IdiomNote k_ukg_classic_2step_P3_bass[] = {{0, 0, 4, 104, 0}, {5, -5, 3, 82, 0}, {14, 3, 1, 78, 0}};
inline constexpr IdiomStab k_ukg_classic_2step_P3_stab[] = {{2, 0, 0x489u, 2, 74}, {10, 10, 0x91u, 2, 70}};
inline constexpr IdiomNote k_ukg_classic_2step_P3_melody[] = {{11, 10, 1, 68, 0}};
inline constexpr IdiomNote k_ukg_dark_skippy_P1_bass[] = {{0, -12, 4, 108, 0}, {5, -7, 3, 86, 0}, {9, -2, 4, 96, 0}, {14, 3, 2, 82, 0}};
inline constexpr IdiomStab k_ukg_dark_skippy_P1_stab[] = {{2, 0, 0x489u, 1, 76}, {6, 8, 0x891u, 1, 82}, {10, 10, 0x91u, 1, 72}, {14, 7, 0x489u, 1, 86}};
inline constexpr IdiomNote k_ukg_dark_skippy_P1_melody[] = {{3, 7, 1, 64, 0}, {11, 10, 1, 70, 0}};
inline constexpr IdiomNote k_ukg_dark_skippy_P2_bass[] = {{0, -12, 4, 108, 0}, {5, -7, 3, 86, 0}, {8, -4, 2, 70, 0}, {9, -2, 4, 98, 0}, {14, 3, 2, 84, 0}};
inline constexpr IdiomStab k_ukg_dark_skippy_P2_stab[] = {{2, 0, 0x4489u, 1, 78}, {6, 8, 0x891u, 1, 84}, {10, 10, 0x291u, 1, 74}, {14, 7, 0x489u, 1, 88}};
inline constexpr IdiomNote k_ukg_dark_skippy_P2_melody[] = {{3, 7, 1, 64, 0}, {9, 5, 1, 52, 0}, {11, 10, 1, 72, 0}};
inline constexpr IdiomNote k_ukg_dark_skippy_P3_bass[] = {{0, -12, 5, 104, 0}, {5, -7, 4, 82, 0}, {14, 3, 2, 78, 0}};
inline constexpr IdiomStab k_ukg_dark_skippy_P3_stab[] = {{2, 0, 0x489u, 2, 74}, {10, 10, 0x91u, 2, 70}};
inline constexpr IdiomNote k_ukg_dark_skippy_P3_melody[] = {{11, 10, 1, 68, 0}};
inline constexpr IdiomNote k_house_deep_offbeat_P1_bass[] = {{2, 0, 1, 104, 0}, {6, 0, 1, 92, 0}, {10, 12, 1, 98, 0}, {14, 0, 1, 90, 0}};
inline constexpr IdiomStab k_house_deep_offbeat_P1_stab[] = {{3, 0, 0x4489u, 1, 78}, {7, 0, 0x4489u, 2, 72}, {11, 5, 0x4489u, 2, 80}};
inline constexpr IdiomNote k_house_deep_offbeat_P1_melody[] = {{15, 10, 1, 64, 0}};
inline constexpr IdiomNote k_house_deep_offbeat_P2_bass[] = {{2, 0, 1, 104, 0}, {6, 0, 1, 92, 0}, {7, -2, 1, 70, 0}, {10, 12, 1, 98, 1}, {14, 0, 1, 90, 0}, {15, -5, 1, 72, 0}};
inline constexpr IdiomStab k_house_deep_offbeat_P2_stab[] = {{3, 0, 0x4489u, 1, 78}, {7, 0, 0x4489u, 2, 72}, {11, 5, 0x4489u, 2, 80}, {14, 5, 0x4489u, 1, 66}};
inline constexpr IdiomNote k_house_deep_offbeat_P2_melody[] = {{5, 7, 2, 60, 0}, {15, 10, 1, 66, 0}};
inline constexpr IdiomNote k_house_deep_offbeat_P3_bass[] = {{2, 0, 2, 100, 0}, {10, 12, 2, 94, 0}};
inline constexpr IdiomStab k_house_deep_offbeat_P3_stab[] = {{3, 0, 0x4489u, 3, 76}, {11, 5, 0x4489u, 3, 78}};

inline constexpr IdiomVariant k_acid_chicago_jack = {"acid_chicago_jack", {{k_acid_chicago_jack_P1_bass, 10, k_acid_chicago_jack_P1_stab, 4, k_acid_chicago_jack_P1_melody, 2}, {k_acid_chicago_jack_P2_bass, 13, k_acid_chicago_jack_P2_stab, 4, k_acid_chicago_jack_P2_melody, 3}, {k_acid_chicago_jack_P3_bass, 8, k_acid_chicago_jack_P3_stab, 2, k_acid_chicago_jack_P3_melody, 1}}};
inline constexpr IdiomVariant k_acid_rolling = {"acid_rolling", {{k_acid_rolling_P1_bass, 14, k_acid_rolling_P1_stab, 4, k_acid_rolling_P1_melody, 2}, {k_acid_rolling_P2_bass, 13, k_acid_rolling_P2_stab, 4, k_acid_rolling_P2_melody, 3}, {k_acid_rolling_P3_bass, 8, k_acid_rolling_P3_stab, 2, k_acid_rolling_P3_melody, 1}}};
inline constexpr IdiomVariant k_lofi_classic_chill = {"lofi_classic_chill", {{k_lofi_classic_chill_P1_bass, 5, k_lofi_classic_chill_P1_stab, 3, k_lofi_classic_chill_P1_melody, 2}, {k_lofi_classic_chill_P2_bass, 6, k_lofi_classic_chill_P2_stab, 3, k_lofi_classic_chill_P2_melody, 3}, {k_lofi_classic_chill_P3_bass, 3, k_lofi_classic_chill_P3_stab, 2, k_lofi_classic_chill_P3_melody, 1}}};
inline constexpr IdiomVariant k_lofi_drunken = {"lofi_drunken", {{k_lofi_drunken_P1_bass, 5, k_lofi_drunken_P1_stab, 3, k_lofi_drunken_P1_melody, 2}, {k_lofi_drunken_P2_bass, 6, k_lofi_drunken_P2_stab, 3, k_lofi_drunken_P2_melody, 3}, {k_lofi_drunken_P3_bass, 3, k_lofi_drunken_P3_stab, 2, k_lofi_drunken_P3_melody, 1}}};
inline constexpr IdiomVariant k_boombap_golden_era = {"boombap_golden_era", {{k_boombap_golden_era_P1_bass, 5, k_boombap_golden_era_P1_stab, 2, k_boombap_golden_era_P1_melody, 2}, {k_boombap_golden_era_P2_bass, 6, k_boombap_golden_era_P2_stab, 3, k_boombap_golden_era_P2_melody, 3}, {k_boombap_golden_era_P3_bass, 3, k_boombap_golden_era_P3_stab, 2, k_boombap_golden_era_P3_melody, 1}}};
inline constexpr IdiomVariant k_boombap_dusty_jazz = {"boombap_dusty_jazz", {{k_boombap_dusty_jazz_P1_bass, 5, k_boombap_dusty_jazz_P1_stab, 2, k_boombap_dusty_jazz_P1_melody, 2}, {k_boombap_dusty_jazz_P2_bass, 6, k_boombap_dusty_jazz_P2_stab, 3, k_boombap_dusty_jazz_P2_melody, 3}, {k_boombap_dusty_jazz_P3_bass, 3, k_boombap_dusty_jazz_P3_stab, 2, k_boombap_dusty_jazz_P3_melody, 1}}};
inline constexpr IdiomVariant k_ukg_classic_2step = {"ukg_classic_2step", {{k_ukg_classic_2step_P1_bass, 4, k_ukg_classic_2step_P1_stab, 4, k_ukg_classic_2step_P1_melody, 2}, {k_ukg_classic_2step_P2_bass, 5, k_ukg_classic_2step_P2_stab, 4, k_ukg_classic_2step_P2_melody, 3}, {k_ukg_classic_2step_P3_bass, 3, k_ukg_classic_2step_P3_stab, 2, k_ukg_classic_2step_P3_melody, 1}}};
inline constexpr IdiomVariant k_ukg_dark_skippy = {"ukg_dark_skippy", {{k_ukg_dark_skippy_P1_bass, 4, k_ukg_dark_skippy_P1_stab, 4, k_ukg_dark_skippy_P1_melody, 2}, {k_ukg_dark_skippy_P2_bass, 5, k_ukg_dark_skippy_P2_stab, 4, k_ukg_dark_skippy_P2_melody, 3}, {k_ukg_dark_skippy_P3_bass, 3, k_ukg_dark_skippy_P3_stab, 2, k_ukg_dark_skippy_P3_melody, 1}}};
inline constexpr IdiomVariant k_house_deep_offbeat = {"house_deep_offbeat", {{k_house_deep_offbeat_P1_bass, 4, k_house_deep_offbeat_P1_stab, 3, k_house_deep_offbeat_P1_melody, 1}, {k_house_deep_offbeat_P2_bass, 6, k_house_deep_offbeat_P2_stab, 4, k_house_deep_offbeat_P2_melody, 2}, {k_house_deep_offbeat_P3_bass, 2, k_house_deep_offbeat_P3_stab, 2, nullptr, 0}}};

}  // namespace GenreIdiom
